# Generated by Codex on 2026-02-11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionselection",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
