# Generated by Codex on 2026-02-11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_subscriptionselection_stripe_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionselection",
            name="stripe_status",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="subscriptionselection",
            name="stripe_cancel_at_period_end",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriptionselection",
            name="stripe_cancel_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscriptionselection",
            name="stripe_current_period_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
