# Generated by Codex on 2026-02-11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_subscriptionselection_status_and_cancel_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionselection",
            name="stripe_current_period_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
