# Generated by Django 6.0.2 on 2026-02-14 00:00

from django.conf import settings
from django.db import migrations, models
from django.db.models import Q
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slop_detection', '0003_slopreportcorrection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlopRateLimitUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, default='', max_length=45)),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slop_rate_limits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(condition=Q(('user__isnull', False)), fields=('user', 'date'), name='slop_rate_limit_user_date_unique'),
                    models.UniqueConstraint(condition=Q(('user__isnull', True)), fields=('ip_address', 'date'), name='slop_rate_limit_ip_date_unique'),
                ],
            },
        ),
    ]
